---
- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
  register: elasticsearch_service_result

- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: not (elasticsearch_service_result is defined and elasticsearch_service_result.changed)
