---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
    ANSIBLE_HASH_BEHAVIOUR: merge
  vars:
    elasticsearch:
      transport_security:
        ca_from: "{{ inventory_hostname }}"
      elasticsearch.yml:
        xpack:
          security:
            enabled: false
  tasks:
    - name: "Include ansible-proserver-elasticsearch"
      ansible.builtin.include_role:
        name: "ansible-proserver-elasticsearch"
