---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure that the cluster is green
      ansible.builtin.uri:
        password: supersecretpassword
        url: http://localhost:9200/_cluster/health
        user: elastic
      register: this
      failed_when: this is failed or this.json.status != "green"
